// get all equipment
    get http://127.0.0.1:8000/api/equipment/sel-all


// get one equipment
    post http://127.0.0.1:8000/api/equipment/sel-one/{id}


// insert equipment
    post http://127.0.0.1:8000/api/equipment/insert
    token: yes
    example:
    {
    "name": "hahaha",
    "category": "CHAIR",
    "desc": "dish",
    "qty": "10000",
    "price": "7000",
    "broken_price": "16000",
    "unit": "un",
    "images": "images/AgqgH4ZJ4YOYDV5u7PoVhUWGFbbya9E8QhrPrTSJ.jpg",
    }

// update equipment
    post http://127.0.0.1:8000/api/equipment/{id}
    token: yes

    example:
    {
    "name": "lalala",
    "category": "CHAIR",
    "desc": "dish",
    "qty": "10000",
    "price": "7000",
    "broken_price": "16000",
    "unit": "un",
    "_method": "put",
    "images": "images/AgqgH4ZJ4YOYDV5u7PoVhUWGFbbya9E8QhrPrTSJ.jpg",
    }


// delete equipment
    delete http://127.0.0.1:8000/api/equipment/delete/{id}
    token: yes