// register
    post http://127.0.0.1:8000/api/register

    example:
    {
        "first_name": "aaa",
        "last_name": "aaa",
        "gender": "MALE",
        "responsibility": "aaa",
        "address": "aaa",
        "phone_number": "55555555",
        "profile_image": null,
        "password": "12345678",
    }

// login
    post http://127.0.0.1:8000/api/login

    example:
    {
        "phone_number": "55555555",
        "password": "12345678",
    }

// logout
    post http://127.0.0.1:8000/api/logout
    token: yes
