// register
    post http://127.0.0.1:8000/api/register

    example:
    {
        "first_name": "aaa",
        "last_name": "aaa",
        "gender": "MALE",
        "responsibility": "aaa",
        "address": "aaa",
        "phone_number": "55555555",
        "profile_image": null,
        "password": "12345678",
    }

// register employee
    post http://127.0.0.1:8000/api/user/employee-register

    example:
    {
        "first_name": "aaa",
        "last_name": "aaa",
        "gender": "MALE",
        "responsibility": "aaa",
        "address": "aaa",
        "phone_number": "55555555",
        "profile_image": null,
        "password": "12345678",
    }

// update user
    post http://127.0.0.1:8000/api/user/update/{id}
    token: yes

    example:
    {
        "first_name": "aaa",
        "last_name": "aaa",
        "gender": "MALE",
        "responsibility": "aaa",
        "address": "aaa",
        "role": "EMPLOYEE",
        "status": "INACTIVE",
        "phone_number": "55555555",
        "profile_image": 1687886792.jpg,
        "password": "12345678",
        "_method": "put",
    }

// update user on app
    post http://127.0.0.1:8000/api/user/app-update/{id}
    token: yes

    example:
    {
        "first_name": "aaa",
        "last_name": "aaa",
        "gender": "MALE",
        "responsibility": "aaa",
        "address": "aaa",
        "role": "EMPLOYEE",
        "status": "INACTIVE",
        "phone_number": "55555555",
        "profile_image": "base64",
        "password": "12345678",
        "_method": "put",
    }

// login
    post http://127.0.0.1:8000/api/login

    example:
    {
        "phone_number": "55555555",
        "password": "12345678",
    }

// logout
    delete http://127.0.0.1:8000/api/logout
    token: yes

// get all user
    get http://127.0.0.1:8000/api//user/sel-all
    token: yes

// get one user
    get http://127.0.0.1:8000/api//user/sel-one


// delete user
    delete http://127.0.0.1:8000/api/user/delete/{id}
    token: yes